version: 2
jobs:
  build:
    docker:
      - image: aergus/latex
    steps:
      - checkout
      - run:
          name: Checkout GURPS LaTeX package
          command: git -C / clone https://github.com/nasfarley88/gurps-latex-package
      - run:
          name: Make GURPS LaTeX package
          command: make -C /gurps-latex-package/source inst
      - run:
          name: Make the projects
          command: make -j$(nproc)
      - run:
          name: Checkout GCS
          command: wget https://github.com/richardwilkes/gcs/releases/download/gcs-4.10.0/gcs-4.10.0-linux.zip && unzip *.zip -d /tmp/gcs
      - run:
          name: PDF the character sheets
          command: cd character_sheets/ && /tmp/gcs/gcs-4.10.0-linux/gcs -pdf *.gcs
      - store_artifacts:
          path: .
